[versions]
kotlin = "2.1.10"

[libraries]
kotlinxCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1"
kotlinxCoroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.1"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
