name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "23"
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check
